name: Github Action Workflow

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Invoking other action
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - id: script
        name: Run script
        run: |
          if (true) {
            Write-Output output="asdasd" >> $env:GITHUB_OUTPUT
          }
      - id: second
        if: ${{ steps.script.outputs.output == "asdasd" }}
        run: |
          Write-Host "got the output from the first one"
          Write-Output output="secondoutput" >> $env:GITHUB_OUTPUT
      - id: third
        run: .github\workflows\bin\script.ps1
        env:
          SECOND_OUTPUT: ${{ steps.second.outputs.output }}
        